; Default properties file for the configurator

[plugframe properties]
;Framework's startlevel to reach
plugframe.framework.startlevel=8

;Message language is English by default.
;Translation available in French (fr_FR).
plugframe.locale=fr_FR

; Minimal declaration of properties of a Gui launcher in order to apply a style sheet
[qt properties]
qt.styleSheet.file=elekdom.qss
