; Configuration file template for text launcher.
; Do not use this file directly for deployment.
; Create a directory containing all the configuration files for a given deployment !

;this ini file defines launcher's properties
;currently the possible properties are:

[plugframe properties]
;Framework's startlevel to reach
plugframe.framework.startlevel=

;Message language is English by default.
;Translation available in French (fr_FR).
plugframe.locale=