// Copyright (C) 2026 ELEKDOM Christophe Mars c.mars@elekdom.fr
//
// This file is part of PlugFrame.
//
// PlugFrame is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// PlugFrame is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with PlugFrame. If not, see <https://www.gnu.org/licenses/>.
//
#include <QSaveFile>
#include <QStringList>
#include <QMessageBox>
#include <QDir>
#include "installationscriptgenerator.h"

int InstallationScriptGenerator::s_lastStep = 11;

//--------------------------------------------------------
// Script skeleton to be generated.
// The TAGs will be replaced by the installation settings.
//--------------------------------------------------------
QString InstallationScriptGenerator::s_runtimeInstall_in =
"{TAG1}"
"# This file is generated by the configurator.\n"
"# It should not be added to the git repository!\n"
"\n"
"############\n"
"# Preamble #\n"
"############\n"
"\n"
"{TAG2}"
"{TAG3}"
"\n"
"message(STATUS \"PF_CONF_PROJECT_SOURCE  = ${PF_CONF_PROJECT_SOURCE}\")\n"
"message(STATUS \"PF_CONF_BUILD_ROOT = ${PF_CONF_BUILD_ROOT}\")\n"
"\n"
"if (NOT PF_CONF_PROJECT_SOURCE STREQUAL PF_PROJECT_SOURCE_DIR)\n"
"  message(FATAL_ERROR \"PF_CONF_PROJECT_SOURCE is not equal to PF_PROJECT_SOURCE_DIR\")\n"
"endif()\n"
"\n"
"if (NOT PF_CONF_BUILD_ROOT STREQUAL PF_RUNTIME_ROOT)\n"
"  message(FATAL_ERROR \"PF_CONF_BUILD_ROOT is not equal to PF_RUNTIME_ROOT\")\n"
"endif()\n"
"\n"
"################################\n"
"# runtime platform directories #\n"
"################################\n"
"\n"
"set(PF_BIN_DIR    \"${PF_CONF_BUILD_ROOT}/bin\")\n"
"set(PF_LIBS_DIR   \"${PF_BIN_DIR}/libs\")\n"
"execute_process(COMMAND \"${CMAKE_COMMAND}\" -E make_directory \"${PF_BIN_DIR}\")\n"
"execute_process(COMMAND \"${CMAKE_COMMAND}\" -E make_directory \"${PF_LIBS_DIR}\")\n"
"\n"
"{TAG4}"
"\n"
"#####################\n"
"# libs installation #\n"
"#####################\n"
"\n"
"{TAG5}"
"\n"
"#################################################\n"
"# installation of application bundles (plugins) #\n"
"#################################################\n"
"\n"
"{TAG6}"
"\n"
"######################################\n"
"# installing the configuration files #\n"
"######################################\n"
"\n"
"# source of configuration files\n"
"###############################\n"
"\n"
"{TAG7}"
"{TAG8}"
"\n"
"set(PF_CONF_PROFILE_DIR \"${PF_CONF_PROFILES_ROOT_DIR}/${PF_CONF_SELECTED_PROFILE_NAME}\")\n"
"if(EXISTS \"${PF_CONF_PROFILE_DIR}\" AND IS_DIRECTORY \"${PF_CONF_PROFILE_DIR}\")\n"
"  message(STATUS \"Installing conf files from: ${PF_CONF_PROFILE_DIR}\")\n"
"\n"
"# installing the configuration files for the launchers\n"
"#########################################################\n"
"\n"
"{TAG9}"
"\n"
"# installing the configuration files for the bundles (plugins)\n"
"##############################################################\n"
"\n"
"{TAG10}"
"\n"
"else()\n"
"  message(STATUS \"Configuration profile directory does not exist: ${PF_CONF_PROFILE_DIR}\")\n"
"  message(STATUS \"Skipping configuration files installation!\")\n"
"endif()\n";

InstallationScriptGenerator::InstallationScriptGenerator(GeneratorDeveloperModeHook *bundleHook, QObject *parent) :
    QObject{parent},
    m_bundleHook{bundleHook},
    m_processingProgressDisplay{nullptr}
{
    connect(this,SIGNAL(startStep(int)),this,SLOT(onStartStep(int)),Qt::QueuedConnection);
    connect(this,SIGNAL(stepFinished(int)),this,SLOT(onStepFinished(int)),Qt::QueuedConnection);
    connect(this,SIGNAL(startRemoving(QString,QWidget*)),this,SLOT(onStartRemoving(QString,QWidget*)),Qt::QueuedConnection);
    connect(this,SIGNAL(removingFinished(bool,QWidget*)),this,SLOT(onRemovingFinished(bool,QWidget*)),Qt::QueuedConnection);
}

InstallationScriptGenerator::~InstallationScriptGenerator()
{

}

void InstallationScriptGenerator::generateInstallationScript(InstallationSettings installationSettings, QWidget *view)
{
    m_scriptGenerationSettings = installationSettings;
    m_runtimeInstall_out = s_runtimeInstall_in;
    m_processingProgressDisplay = new QProgressDialog(tr("Generating installation script..."),
                                                      QString(),   // no Cancel button
                                                      0,
                                                      s_lastStep, // number of steps
                                                      view);
    m_processingProgressDisplay->setWindowFlags(Qt::Dialog | Qt::FramelessWindowHint);
    m_processingProgressDisplay->setWindowModality(Qt::WindowModal);
    m_processingProgressDisplay->setAutoClose(false);
    m_processingProgressDisplay->setAutoReset(false);
    m_processingProgressDisplay->show();
    m_processingProgressDisplay->setValue(0);
    emit startStep(1);
}

void InstallationScriptGenerator::removeInstallation(QString projectBuildRoot, QWidget *view)
{
    QDir binDir{projectBuildRoot};

    if (binDir.cd("bin"))
    {
        QString msg{tr("Removing: ") + binDir.absolutePath()};

        m_processingProgressDisplay = new QProgressDialog(msg,
                                                          QString(),   // no Cancel button
                                                          0,
                                                          1,
                                                          view);
        m_processingProgressDisplay->setWindowFlags(Qt::Dialog | Qt::FramelessWindowHint);
        m_processingProgressDisplay->setWindowModality(Qt::WindowModal);
        m_processingProgressDisplay->setAutoClose(false);
        m_processingProgressDisplay->setAutoReset(false);
        m_processingProgressDisplay->show();
        m_processingProgressDisplay->setValue(0);

        emit startRemoving(binDir.absolutePath(),view);
    }
}

void InstallationScriptGenerator::onStartStep(int step)
{
    switch(step)
    {
        case 1:
            fillinTagScriptName();
            break;
        case 2:
            fillinTagProjectSource();
            break;
        case 3:
            fillinTagBuildRoot();
            break;
        case 4:
            fillinTagAppsDir();
            break;
        case 5:
            fillinTagLibs();
            break;
        case 6:
            fillinTagAppsBundles();
            break;
        case 7:
            fillinTagConfProfilesRootDir();
            break;
        case 8:
            fillinTagConfSelectedProfile();
            break;
        case 9:
            fillinTagAppsConfFiles();
            break;
        case 10:
            fillinTagBundlesConfFiles();
            break;
        case 11:
            writeToFile();
            break;
    }

    emit stepFinished(step);
}

void InstallationScriptGenerator::onStepFinished(int step)
{
    m_processingProgressDisplay->setValue(step);
    if (step == s_lastStep)
    {
        m_processingProgressDisplay->hide();
        m_processingProgressDisplay->deleteLater();
        m_processingProgressDisplay = nullptr;
    }
    else
    {
        emit startStep(step + 1);
    }
}

void InstallationScriptGenerator::onStartRemoving(QString dirPath, QWidget *view)
{
    bool ok;
    QDir dir{dirPath};

    ok = dir.removeRecursively();
    m_processingProgressDisplay->setValue(1);

    emit removingFinished(ok,view);
}

void InstallationScriptGenerator::onRemovingFinished(bool ok,QWidget *view)
{
    QString msg;

    m_processingProgressDisplay->hide();
    delete m_processingProgressDisplay;
    m_processingProgressDisplay = nullptr;

    if (ok)
    {
        msg = tr("removing success.");
    }
    else
    {
        msg = tr("removing failed.");
    }

    QMessageBox::information(view,tr("Developer Mode"),msg);
}

void InstallationScriptGenerator::fillinTagScriptName()
{
    QString fieldValue{"# %1\n# Installation settings identifier: %2\n"};

    fieldValue = fieldValue.arg(m_scriptGenerationSettings.m_scriptName,m_scriptGenerationSettings.m_installationSettingsIdentifier);
    m_runtimeInstall_out.replace("{TAG1}",fieldValue);
}

void InstallationScriptGenerator::fillinTagProjectSource()
{
    QString fieldValue{"set(PF_CONF_PROJECT_SOURCE \"%1\")\n"};

    fieldValue = fieldValue.arg(m_scriptGenerationSettings.m_projectSourcePath);
     m_runtimeInstall_out.replace("{TAG2}",fieldValue);
}

void InstallationScriptGenerator::fillinTagBuildRoot()
{
    QString fieldValue{"set(PF_CONF_BUILD_ROOT \"%1\")\n"};

    fieldValue = fieldValue.arg(m_scriptGenerationSettings.m_projectBuildRoot);
    m_runtimeInstall_out.replace("{TAG3}",fieldValue);
}

void InstallationScriptGenerator::fillinTagAppsDir()
{
    QString fieldValue;

    for (auto i=0;i<m_scriptGenerationSettings.m_applicationArtefactList.size();i++)
    {
        ApplicationArtefact cur{m_scriptGenerationSettings.m_applicationArtefactList[i]};

        if (!cur.m_deletedFlag && !cur.m_newlyFlag)
        {
            QString istr{QVariant(i + 1).toString()};
            QString fieldAppDirLine1{"set(APP%1_NAME \"%2\")\n"};
            QString fieldAppDirLine2{"set(PF_CONF_APP%1_DIR \"${PF_BIN_DIR}/${APP%2_NAME}\")\n"};
            QString fieldAppDirLine3{"pf_create_app_subdirs(PF_CONF_APP%1_DIR)\n"};

            fieldAppDirLine1 = fieldAppDirLine1.arg(istr,cur.m_applicationName);
            fieldAppDirLine2 = fieldAppDirLine2.arg(istr,istr);
            fieldAppDirLine3 = fieldAppDirLine3.arg(istr);

            fieldValue.append(fieldAppDirLine1);
            fieldValue.append(fieldAppDirLine2);
            fieldValue.append(fieldAppDirLine3);
        }
    }

    m_runtimeInstall_out.replace("{TAG4}",fieldValue);
}

void InstallationScriptGenerator::fillinTagLibs()
{
    QString fieldValue;

    for (auto i=0;i<m_scriptGenerationSettings.m_libsArtefactList.size();i++)
    {
        LibsArtefact cur{m_scriptGenerationSettings.m_libsArtefactList[i]};

        if (!cur.m_deletedFlag && !cur.m_newlyFlag)
        {
            QString fieldLibLine1{"pf_copy_lib(\"${PF_LIBS_DIR}\"\n"};
            QString fieldLibLine2{"\"${PF_CONF_BUILD_ROOT}%1\"\n"};
            QString fieldLibLine3{"\"${PF_CONF_BUILD_ROOT}%1\"\n"};
            QString fieldLibLine4{"\"${PF_CONF_BUILD_ROOT}%1\")\n"};

            fieldLibLine2 = fieldLibLine2.arg(cur.m_libName);
            fieldLibLine3 = fieldLibLine3.arg(cur.m_soName);
            fieldLibLine4 = fieldLibLine4.arg(cur.m_linkerName);

            fieldValue.append(fieldLibLine1);
            fieldValue.append(fieldLibLine2);
            fieldValue.append(fieldLibLine3);
            fieldValue.append(fieldLibLine4);
        }
    }

    m_runtimeInstall_out.replace("{TAG5}",fieldValue);
}

void InstallationScriptGenerator::fillinTagAppsBundles()
{
    QString fieldValue;

    for (auto i=0;i<m_scriptGenerationSettings.m_applicationArtefactList.size();i++)
    {
        ApplicationArtefact cur{m_scriptGenerationSettings.m_applicationArtefactList[i]};

        if (!cur.m_deletedFlag && !cur.m_newlyFlag)
        {
            QString istr{QVariant(i + 1).toString()};
            for (auto j=0;j<m_scriptGenerationSettings.m_applicationArtefactList[i].m_bundleArtefactList.size();j++)
            {
                BundleArtefact curB{m_scriptGenerationSettings.m_applicationArtefactList[i].m_bundleArtefactList[j]};

                if (!curB.m_deletedFlag && !curB.m_newlyFlag)
                {
                    QString fieldAppBundleLine1{"pf_copy_bundle(\"${PF_CONF_APP%1_DIR}\"\n"};
                    QString fieldAppBundleLine2{"\"%1\"\n"};
                    QString fieldAppBundleLine3{"\"${PF_CONF_BUILD_ROOT}%1\")\n"};

                    fieldAppBundleLine1 = fieldAppBundleLine1.arg(istr);
                    fieldAppBundleLine2 = fieldAppBundleLine2.arg(m_scriptGenerationSettings.m_applicationArtefactList[i].m_bundleArtefactList[j].m_bundleName);
                    fieldAppBundleLine3 = fieldAppBundleLine3.arg(m_scriptGenerationSettings.m_applicationArtefactList[i].m_bundleArtefactList[j].m_bundlePlugin);

                    fieldValue.append(fieldAppBundleLine1);
                    fieldValue.append(fieldAppBundleLine2);
                    fieldValue.append(fieldAppBundleLine3);
                }
            }
        }
    }

    m_runtimeInstall_out.replace("{TAG6}",fieldValue);
}

void InstallationScriptGenerator::fillinTagConfProfilesRootDir()
{
    QString fieldValue{"set(PF_CONF_PROFILES_ROOT_DIR \"%1\")\n"};

    fieldValue = fieldValue.arg(m_scriptGenerationSettings.m_configurationFilesRepository);

    m_runtimeInstall_out.replace("{TAG7}",fieldValue);
}

void InstallationScriptGenerator::fillinTagConfSelectedProfile()
{
    QString fieldValue{"set(PF_CONF_SELECTED_PROFILE_NAME \"%1\")\n"};

    fieldValue = fieldValue.arg(m_scriptGenerationSettings.m_configurationProfile);

    m_runtimeInstall_out.replace("{TAG8}",fieldValue);
}

void InstallationScriptGenerator::fillinTagAppsConfFiles()
{
    QString fieldValue;

    for (auto i=0;i<m_scriptGenerationSettings.m_applicationArtefactList.size();i++)
    {
        ApplicationArtefact cur{m_scriptGenerationSettings.m_applicationArtefactList[i]};

        if (!cur.m_deletedFlag && !cur.m_newlyFlag)
        {
            QStringList fileList;
            QString istr{QVariant(i + 1).toString()};

            fileList = m_bundleHook->getLauncherConfFileList(m_scriptGenerationSettings.m_projectName,cur.m_applicationName);
            for (auto j=0;j<fileList.size();j++)
            {
                QString fieldAppConfFileLine1{"pf_copy_conf_file(\n\"${PF_CONF_PROFILE_DIR}/${APP%1_NAME}/%2\"\n"};
                QString fieldAppConfFileLine2{"\"${PF_CONF_APP%1_DIR}/conf\")\n"};

                fieldAppConfFileLine1 = fieldAppConfFileLine1.arg(istr,fileList[j]);
                fieldAppConfFileLine2 = fieldAppConfFileLine2.arg(istr);

                fieldValue.append(fieldAppConfFileLine1);
                fieldValue.append(fieldAppConfFileLine2);
            }
        }
    }

    m_runtimeInstall_out.replace("{TAG9}",fieldValue);
}

void InstallationScriptGenerator::fillinTagBundlesConfFiles()
{
    QString fieldValue;

    for (auto i=0;i<m_scriptGenerationSettings.m_applicationArtefactList.size();i++)
    {
        ApplicationArtefact cur{m_scriptGenerationSettings.m_applicationArtefactList[i]};

        if (!cur.m_deletedFlag && !cur.m_newlyFlag)
        {
            QString istr{QVariant(i + 1).toString()};
            for (auto j=0;j<m_scriptGenerationSettings.m_applicationArtefactList[i].m_bundleArtefactList.size();j++)
            {
                BundleArtefact curB{m_scriptGenerationSettings.m_applicationArtefactList[i].m_bundleArtefactList[j]};

                if (!curB.m_deletedFlag && !curB.m_newlyFlag)
                {
                    QStringList fileList;

                    fileList = m_bundleHook->getBundleConfFileList(m_scriptGenerationSettings.m_projectName,cur.m_applicationName,curB.m_bundleName);
                    for (auto k=0;k<fileList.size();k++)
                    {
                        QString fieldBundleConfFileLine1{"pf_copy_conf_file(\n\"${PF_CONF_PROFILE_DIR}/${APP%1_NAME}/%2/%3\"\n"};
                        QString fieldBundleConfFileLine2{"\"${PF_CONF_APP%1_DIR}/bundles/%2/conf\")\n"};

                        fieldBundleConfFileLine1 = fieldBundleConfFileLine1.arg(istr,curB.m_bundleName,fileList[k]);
                        fieldBundleConfFileLine2 = fieldBundleConfFileLine2.arg(istr,curB.m_bundleName);

                        fieldValue.append(fieldBundleConfFileLine1);
                        fieldValue.append(fieldBundleConfFileLine2);
                    }
                }
            }
        }
    }

    m_runtimeInstall_out.replace("{TAG10}",fieldValue);
}

void InstallationScriptGenerator::writeToFile()
{
    QString scriptFullName{m_scriptGenerationSettings.m_projectSourcePath + QDir::separator() + "cmake" + QDir::separator() + m_scriptGenerationSettings.m_scriptName};
    QByteArray buffer{m_runtimeInstall_out.toUtf8()};
    QSaveFile outFile{scriptFullName};
    bool ok;

    ok = outFile.open(QIODevice::WriteOnly);
    if (ok)
    {
        ok = outFile.write(buffer) == buffer.size();
    }
    if (ok)
    {
        outFile.commit();
    }
}
